[project]
name = "example-project"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "database-core",
    "database-util",
    "environments",
    "migrations",
    "models",
]

[build-system]
requires = ["uv_build>=0.11.18,<0.12"]
build-backend = "uv_build"

[tool.uv.workspace]
members = ["database/database_core", "database/database_util", "database/models", "database/migrations", "database/environments"]

[tool.uv.sources]
database-core = { workspace = true }
database-util = { workspace = true }
models = { workspace = true }
migrations = { workspace = true }
environments = { workspace = true }

[dependency-groups]
dev = [
    "alembic>=1.19.0",
    "copier>=9.17.1",
    "inflection>=0.5.1",
    "psycopg[binary]>=3.3.4",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "pytest-alembic>=0.12.1",
    "ruff>=0.16.2",
    "sqlacodegen>=4.0.4",
    "sqlalchemy>=2.0.51",
    "sqlmodel>=0.0.39",
    "tomlkit>=0.15.1",
    "typer>=0.27.1",
]
