[project]
name = "copier_template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "copier>=9.15.1",
    "tomlkit>=0.15.0",
    "typer>=0.26.6",
]

[project.urls]
Homepage = ""
Documentation = ""
Repository = ""

[project.scripts]
copier = "copier_template.__main__:main"

[build-system]
requires = ["uv_build>=0.11.18,<0.12"]
build-backend = "uv_build"


[tool.pytest.ini_options]
norecursedirs = [
    "*.egg",
    ".*",
    "_darcs",
    "build",
    "CVS",
    "dist",
    "node_modules",
    "venv",
    "{arch}",
    "example",
]

[tool.ruff]
exclude = ["example"]

[tool.uv.workspace]
members = []
exclude = ["example"]
