[project]
name = "copier_template"
version = "0.1.9"
description = "Meta-template for creating copier projects"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "copier>=9.15.1",
    "inflection>=0.5.1",
    "pytest>=9.1.1",
    "tomlkit>=0.15.0",
    "typer>=0.26.6",
]

[project.scripts]
copier-template = "copier_template.__main__:main"
copier_template = "copier_template.__main__:main"

[project.urls]
Homepage = "https://github.com/Phazebreak-Coatings-Inc/copier-template"
Documentation = "https://phazebreak-coatings-inc.github.io/copier-template"
Repository = "https://github.com/Phazebreak-Coatings-Inc/copier-template/"

[build-system]
requires = ["uv_build>=0.11.18,<0.12"]
build-backend = "uv_build"


[tool.pytest.ini_options]
norecursedirs = [
    "*.egg",
    ".*",
    "_darcs",
    "build",
    "CVS",
    "dist",
    "node_modules",
    "venv",
    "{arch}",
    "example",
    "template",
    ".venv"
]
testpaths = ["tests"]
markers = ["slow"]

[tool.ruff]
exclude = ["example", "template"]

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes (syntax, undefined names, etc.)
    "I",    # isort (clean and sorted imports)
    "UP",   # pyupgrade (upgrades syntax to your target Python version)
    "B",    # flake8-bugbear (catches design flaws and subtle bugs)
    "SIM",  # flake8-simplify (suggests simpler code structures)
    "C90",  # mccabe (prevents overly complex functions)
]

[tool.uv.workspace]
members = []
exclude = ["example", "template"]

[dependency-groups]
dev = [
    "ssort>=0.17.0",
]
