from pathlib import Path

DIR_DATABASE = Path(__file__).parent.parent.parent.parent.parent
WS_ENVIRONMENTS = DIR_DATABASE / "environments"
WS_MIGRATIONS = DIR_DATABASE / "migrations"
WS_MODELS = DIR_DATABASE / "models"
TABLES_SQL = WS_MODELS / "tables.sql"
PKG_MODELS = WS_MODELS / "src" / "models"
PKG_MIGRATIONS = WS_MIGRATIONS / "src" / "migrations"
TESTS_MIGRATIONS = WS_MIGRATIONS / "tests"
PKG_ENVIRONMENTS = WS_ENVIRONMENTS / "src" / "environments"
DIR_SEEDS = PKG_MIGRATIONS / "seeds"
INIT_MODELS = PKG_MODELS / "__init__.py"
DIR_VERSIONS = PKG_MIGRATIONS / "versions"
PKG_CLUSTERS = WS_ENVIRONMENTS / "clusters"
PKG_PROD = PKG_CLUSTERS / "prod"
ENV_PROD = PKG_PROD / ".env.prod"
PKG_DEV = PKG_CLUSTERS / "dev"
ENV_DEV = PKG_DEV / ".env.dev"
ENV_DEV_COMPOSE = PKG_DEV / "compose.dev.yml"
PKG_STAGING = PKG_CLUSTERS / "staging"
ENV_STAGING = PKG_STAGING / ".env.staging"
DIR_BACKFILLS = PKG_MIGRATIONS / "backfills"
