from pathlib import Path
from typing import Annotated
from pydantic import validate_call

import typer

from ...utils import (
    DryRun,
    EnvArg,
    alembic_heads,
    alembic_test,
    alembic_env,
    alembic_migrate,
    sh,
    alembic,
    migration_settings as ms,
    migration_database as mdb,
    alembic_check,
    DIR_SEEDS,
    DIR_VERSIONS,
    git_bot,
    get_database_setting,
    execute_seeds,
    generate_seed_file,
    e,
    SeedableEnvArg,
    Revision,
    RevisionOption,
    BackfillException,
    latest_rev,
    write_backfill_stub
)


app = typer.Typer()


@app.command(
    help="Start up the migrations database for autogenerating alembic revisions."
)
@e
@validate_call
def up(
):
    return ms.up()


@app.command(help="Shut down the migrations database.")
def down():
    return ms.down()


@app.command(help="Test the alembic revisions generated.")
@e
def test(
    throw: Annotated[
        bool, typer.Option("-t", "--throw", help="Raise on test failure.")
    ] = False,
    seed: Annotated[bool, typer.Option("-s", "--seed", help="Test seed runs")] = False,
):
    with mdb():
        alembic_test(typ="migrations" if not seed else "seeds", throw=throw)


@app.command(
    help="Start the migrations database to autogenerate a revision, then clean up."
)
@e
def migrate(message: Annotated[str, typer.Option("-m", "--message")] = ""):
    with mdb():
        alembic_migrate(message)
        alembic_test(throw=True)


@app.command(help="Apply reviewed migrations to an environment.")
@e
def apply(
    env: EnvArg = alembic_env,
    target: str = "head",
    interactive: Annotated[
        bool,
        typer.Option("-i", "--interactive", help="Whether to confirm application."),
    ] = True,
):
    if interactive:
        typer.confirm(f"Upgrade {env} to {target}?", abort=True)
    alembic(f"upgrade {target}", env)


@app.command(help="Check if the database needs to be migrated.")
@e
def check():
    with mdb():
        alembic_check()


@app.command(help="Generate the first (baseline) revision, even if empty.")
@e
def init():
    if alembic_heads():
        typer.secho(
            "Revisions already exist, use 'migrate' instead.",
            fg=typer.colors.RED,
            err=True,
        )
        raise typer.Exit(1)
    with mdb():
        sh(
            'alembic -x initial=true revision --autogenerate -m "initial"',
            check=True,
        )
        alembic_test(throw=True)

@app.command(help="Seed the database with anything decorated with 'migrations.seed'.")
@e
@validate_call
def seed(
    env: SeedableEnvArg,
    n: Annotated[
        str | None,
        typer.Option(
            "--generate",
            "-g",
            help=f"Generate a seed file with '--g {{ name }}' It will arrive in ...{Path(*DIR_SEEDS.parts[-4:])}. The environment variable is for specifying in what environment the seed should run.",
        ),
    ] = None,
    d: DryRun = False,
):
    if n:
        generate_seed_file(env=env, name=n, dry_run=d)
        return
    execute_seeds(env=env, dry_run=d, confirm=True)

@app.command(help="Create a backfill stub. Defaults to the latest revision.")
@e
@validate_call
def backfill(
    rev: RevisionOption | None = None,
    message: Annotated[
        str | None,
        typer.Option("-m", "--message", help="Create a new revision for a backfill."),
    ] = None,
):
    if rev and message:
        raise BackfillException("Pass --for or --message, not both.")

    if message:
        sh(f'alembic revision -m "{message}"', check=True)
    
    rev = rev or latest_rev()
    write_backfill_stub(rev)

@app.command(
    help="Run a autonomous CICD workflow that checks for drift, tests, and commits to the current branch"
)
@e
def cicd(
    check: Annotated[
        bool, typer.Option("-c", "--check", help="Don't commit autogenerated revisions.")
    ] = False,
):
    with mdb():
        try:
            alembic_check()
            drift = False
        except typer.Exit:
            drift = True

        if not drift:
            alembic_test(throw=True)
            return

        if check:
            typer.secho("Migration drift detected.", fg=typer.colors.RED, err=True)
            raise typer.Exit(1)

        with git_bot("chore: autogenerate alembic revision", DIR_VERSIONS):
            alembic_migrate()
            alembic_test(throw=True)
            typer.secho("Generated revision", fg=typer.colors.GREEN)


@app.command(
    help="Apply migrations to staging and prod. Only use this once the migrations are actually on main, else you could have broken versioning."
)
@e
def cicd_apply():
    for env in ["staging", "prod"]:
        s = get_database_setting(env)  # type: ignore
        s.ping()
        apply(env, interactive=False)  # type: ignore
