COPIER_REPO = "gh:Phazebreak-Coatings-Inc/alembic-environment"
ANSWERS_FILE = ".copier-answers.yml"
EXAMPLE_NAME = "example"
EXAMPLE_PROJECT_NAME = "example_project"

WORKSPACE = {}
## ENTER IN THE STYLE OF
# { "SOME DEPENDENCY NAME": "SOME DEPENDENDENCY FILE LOCATION"}

SCRIPTS = {}
## ENTER IN THE STYLE OF
# { "SOME SCRIPT NAME": "SOME PATH TO THE SCRIPT VIA PYTHON MODULE"}

PACKAGES = []

EXAMPLE_PRESENT = []
